title: Ran Ren's Homepage
page-top-title: Ran Ren 任冉
top-section-bg-text: Embrace the future
home-subtitle: Yourname&ensp;|&ensp;上杉绘梨衣
copyright-text: '&copy; Ran Ren 2023-2026. All Rights Reserved.'
